services:
  vayu-suchak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vayu-suchak-app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
